spring:
  application:
    name: dial-relay

server:
  error:
    include-message: always
  port: 9092
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

management:
  endpoints:
    web:
      exposure:
        include: health

dial:
  relay:
    messaging:
      security:
        signature:
          ttl: PT1M
          enabled: false # Disable until Mobile app is ready
          algorithm: EdDSA
    store:
      name: map # redis and map stores available
      maxSize: 1000000 # used by map store
      durationInSeconds: 172800 # used by map store