# Builds pushes and merges on master branch
name: Master branch build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project backend and run default test suite
        run: ./mvnw clean package
        env:
          MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120" # Github-on-Azure tweaks - https://github.com/actions/virtual-environments/issues/1499

      - uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: dial-relay-app/target/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Build and push Docker images to ECR registry
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          ECR_REPOSITORY: "dial-relay"
          IMAGE_TAG: "latest"
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
          docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

      - uses: google-github-actions/setup-gcloud@master

      - name: build and push to GCP registry
        uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: "eu.gcr.io"
          project_id: "ploohid"
          image_name: "dial-relay"
          image_tag: "latest"

  build-and-push-to-gcr:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: jar-artifact

      - run: ls dial-relay-app/target/
      #
      #      - uses: google-github-actions/setup-gcloud@master
      #
      #      - uses: RafikFarhad/push-to-gcr-github-action@v4
      #        with:
      #          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
      #          registry: eu.gcr.io
      #          project_id: ploohid
      #          image_name: dial-relay
      #          image_tag: latest